FROM rust:1.71.1 as build-env
WORKDIR /app
ADD . /app
RUN rm -rf target
RUN cargo build --release --features=libsqlite3-sys

FROM gcr.io/distroless/cc-debian10
COPY --from=build-env /app/target/release/xunit_repo /
CMD ["./xunit_repo"]
